// Farmacia Pura Vida — a Costa Rican pharmacy replaces paper receipts with digital ones.
// Storage keeps the receipt files, Cosmos DB (serverless) keeps sales records, a Static Web App is the front end.
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

@allowed(['LRS', 'GRS'])
@description('Storage redundancy: LRS keeps 3 copies in one datacenter, GRS also copies to a paired region.')
param redundancy string = 'LRS'

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: {
    labName: labName
    location: location
    tags: tags
    redundancy: redundancy
  }
}

output url string = lab.outputs.url
output staticSiteName string = lab.outputs.staticSiteName
output storageAccount string = lab.outputs.storageAccount
output cosmosEndpoint string = lab.outputs.cosmosEndpoint
