// Coffee farms: photo archive. Storage tiers, lifecycle rules, soft delete, versioning, plus Files, Queue and Table for comparison.
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

@allowed(['LRS', 'GRS'])
param redundancy string = 'LRS'

@description('Keep every version of a changed blob.')
param enableVersioning bool = true

@minValue(1)
@maxValue(90)
@description('Days before a blob moves to Cool; Archive after three times as many, delete after twelve times.')
param lifecycleDays int = 30

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: {
    labName: labName
    location: location
    tags: tags
    redundancy: redundancy
    enableVersioning: enableVersioning
    lifecycleDays: lifecycleDays
  }
}

// Opens the storage account in the portal (containers, lifecycle management, file share, queue and table are all there).
output url string = 'https://portal.azure.com/#@/resource${lab.outputs.accountId}/overview'
output storageAccount string = lab.outputs.name
output container string = 'fincas'
