// Cooperativa Ahorro Verde: a Foundry agent. A model deployment and a project, with the cooperative's documents and the
// client scripts in storage. The agent itself is created live in the Foundry portal.
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

@description('Model deployments (name, model, version, capacity in thousands of tokens per minute), built by labctl.')
param deployments array

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: {
    labName: labName
    location: location
    tags: tags
    deployments: deployments
  }
}

// Opens Microsoft Foundry, where the class creates and tests the agent.
output url string = 'https://ai.azure.com/'
output aiAccount string = lab.outputs.aiAccount
output projectEndpoint string = lab.outputs.projectEndpoint
output storageAccount string = lab.outputs.storageAccount
