import { existsSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { BLUEPRINTS, getBlueprint, stagesFor } from "../server/labs/blueprints.ts";
import { bicepPath, compileBlueprint } from "../server/labs/compile.ts";
import { evaluateFeasibility, type AzureFacts } from "../server/labs/feasibility.ts";
import { labResourceTypes } from "../server/labs/engine.ts";

const hasBicep = (() => {
  const p = bicepPath();
  return p !== "bicep" ? existsSync(p) : false;
})();

type Template = {
  parameters: Record<string, unknown>;
  outputs: Record<string, unknown>;
  resources: { type: string; name: string; properties?: { template?: { resources?: unknown[] } } }[];
};

describe("every blueprint", () => {
  it("is a showcase entry with a filled-in scenario", () => {
    for (const b of BLUEPRINTS) {
      expect(b.scenario?.story.length, b.id).toBeGreaterThan(100);
      expect(b.scenario?.objectives.length, b.id).toBeGreaterThanOrEqual(3);
      expect(b.scenario?.exams.length, b.id).toBeGreaterThanOrEqual(1);
      expect(b.id, b.id).toMatch(/^[a-z0-9-]+$/);
      expect(b.code, b.id).toMatch(/^[a-z0-9]{2,10}$/);
    }
    expect(new Set(BLUEPRINTS.map((b) => b.code)).size).toBe(BLUEPRINTS.length);
  });

  it.skipIf(!hasBicep).each(BLUEPRINTS.map((b) => [b.id]))("%s compiles and its template matches the definition", async (id) => {
    const b = getBlueprint(id);
    const t = (await compileBlueprint(b.id)) as unknown as Template;
    // Every parameter the engine sends exists in the template (labName, location and tags are added by the engine).
    const hookParams = (b.paramHooks ?? []).flatMap((h) => Object.keys(h.validateWith ?? {}));
    for (const key of ["labName", "location", "tags", ...Object.keys(b.armParams(b.schema.parse({}), { owner: "x" })), ...hookParams]) expect(t.parameters, key).toHaveProperty(key);
    // The gate reads `url`; the progress view looks for one nested deployment per step.
    expect(t.outputs).toHaveProperty("url");
    const nested = (t.resources.find((r) => r.name === "lab")?.properties?.template?.resources ?? []) as { type: string; name: string }[];
    const modules = nested.filter((r) => r.type === "Microsoft.Resources/deployments").map((r) => r.name);
    for (const s of b.steps(b.schema.parse({}))) expect(modules, s.name).toContain(s.name);
    // Secrets stay secure parameters.
    for (const key of hookParams) expect((t.parameters[key] as { type: string }).type, key).toBe("securestring");
  }, 60_000);
});

describe("cr-taller-servidores", () => {
  const b = getBlueprint("cr-taller-servidores");

  it("offers B-series sizes only and checks the chosen one against quota", () => {
    expect(b.fields.find((f) => f.key === "vmSize")!.options!.every((o) => o.value.startsWith("Standard_B"))).toBe(true);
    expect(b.vmSizes!(b.schema.parse({ vmSize: "Standard_B2s" }))).toEqual(["Standard_B2s"]);
    expect(() => b.schema.parse({ vmSize: "Standard_NC6" })).toThrow();
  });

  it("prices the VM, disk, IP and plan, and the free plan costs nothing", () => {
    const free = b.meters(b.schema.parse({}));
    expect(free.map((m) => m.label)).toEqual(["VM B1s", "Standard SSD disk (30 GB)", "Public IP", "App Service Free"]);
    expect(free.at(-1)!.fixedHourly).toBe(0);
    const basic = b.meters(b.schema.parse({ vmSize: "Standard_B2s", paasTier: "B1" }));
    expect(basic[0]).toMatchObject({ skuName: "B2s", meterName: "B2s" });
    expect(basic.at(-1)).toMatchObject({ skuName: "B1", productName: "Azure App Service Basic Plan - Linux" });
  });

  it("has the admin password generated by labctl, never asked for", () => {
    expect(b.paramHooks).toEqual([expect.objectContaining({ hook: "vm-password" })]);
    expect(Object.keys(b.armParams(b.schema.parse({}), { owner: "x" }))).not.toContain("adminPassword");
  });

  it("offers the cheaper variants when the roomier setup is chosen", () => {
    const roomier = b.schema.parse({ vmSize: "Standard_B2s", paasTier: "B1" });
    expect(b.alternatives!(roomier).map((a) => a.params)).toEqual([{ vmSize: "Standard_B1s" }, { paasTier: "F1" }]);
    expect(b.alternatives!(b.schema.parse({}))).toEqual([]);
    for (const p of b.presets!) expect(b.schema.safeParse(p.params).success).toBe(true);
  });

  it.skipIf(!hasBicep)("opens only HTTP, and ships a page whose hosting text matches each side", async () => {
    const json = JSON.stringify(await compileBlueprint(b.id));
    // Only port 80 is allowed in; SSH (22) and RDP (3389) never appear as rules.
    expect(json).toMatch(/"destinationPortRange":\s*"80"/);
    expect(json).not.toMatch(/"destinationPortRange":\s*"(22|3389|\*)"/);
    // Both hosts get the same page, with their own "who looks after it" answers (ARM fills them in at deploy time).
    expect(json).toContain("'__HOST__', 'Máquina virtual (IaaS)'), '__OSWHO__', 'Usted'), '__RUNWHO__', 'Usted'");
    expect(json).toContain("'__HOST__', 'App Service (PaaS)'), '__OSWHO__', 'Azure'), '__RUNWHO__', 'Azure'");
  }, 60_000);
});

describe("cr-farmacia-recibos", () => {
  const b = getBlueprint("cr-farmacia-recibos");

  it("is a showcase blueprint with its scenario filled in", () => {
    expect(b.category).toBe("Showcase");
    expect(b.scenario?.story.length).toBeGreaterThan(100);
    expect(b.scenario?.objectives.length).toBeGreaterThanOrEqual(3);
    expect(b.scenario?.exams.join(" ")).toMatch(/AZ-900/);
  });

  it("costs nothing while idle and gates on the front end without blocking", () => {
    expect(b.meters(b.schema.parse({})).every((m) => m.fixedHourly === 0)).toBe(true);
    const gate = stagesFor(b, b.schema.parse({}))[0]!.gate!;
    expect(gate).toMatchObject({ kind: "http-ok", blocking: false });
  });

  it("rejects an unsupported redundancy", () => {
    expect(() => b.schema.parse({ redundancy: "RA-GRS" })).toThrow();
    expect(b.armParams(b.schema.parse({ redundancy: "GRS" }), { owner: "x" })).toEqual({ redundancy: "GRS" });
  });

  it("does not fail the region check for Static Web Apps outside its few regions", () => {
    const facts: AzureFacts = {
      providers: { "Microsoft.Web": { registrationState: "Registered", resourceTypes: [{ resourceType: "staticSites", locations: ["Central US"] }] } },
      errors: {},
    };
    const input = (regionFree?: string[]) => ({
      region: "eastus",
      enabledRegions: ["eastus"],
      ttlHours: 8,
      hourly: 0,
      resourceTypes: ["Microsoft.Web/staticSites"],
      regionFree,
      rules: [],
      deployMinutes: [3, 8] as [number, number],
      budget: { monthlyUsd: 600 },
    });
    expect(evaluateFeasibility(input(), facts).find((c) => c.id === "region")!.status).toBe("fail");
    expect(evaluateFeasibility(input(b.regionFree), facts).find((c) => c.id === "region")!.status).toBe("pass");
    expect(labResourceTypes(b, b.schema.parse({}))).toContain("Microsoft.Web/staticSites");
  });

  it("is registered exactly once", () => {
    expect(BLUEPRINTS.filter((x) => x.id === "cr-farmacia-recibos")).toHaveLength(1);
  });
});
