// Tourist reviews — Azure AI Language and Translator on synthetic Spanish and English hotel reviews.
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: { labName: labName, location: location, tags: tags }
}

// Opens Language Studio, where students run sentiment analysis and key-phrase extraction.
output url string = 'https://language.cognitive.azure.com/'
output aiAccount string = lab.outputs.aiAccount
output endpoint string = lab.outputs.endpoint
output storageAccount string = lab.outputs.storageAccount
output container string = lab.outputs.container
