// Municipalidad de Grecia: who can do what. Three identities with roles at three scopes, and a web app whose
// managed identity reads a report from storage only while it has the role.
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

@allowed(['F1', 'B1'])
param appTier string = 'F1'

@description('Give the web app its Storage Blob Data Reader role at the start. The class removes it and adds it back.')
param appHasAccess bool = true

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: {
    labName: labName
    location: location
    tags: tags
    appTier: appTier
    appHasAccess: appHasAccess
  }
}

output url string = lab.outputs.url
output siteName string = lab.outputs.siteName
output storageAccount string = lab.outputs.storageAccount
output container string = 'informes'
