// Branch network: a hub with two spokes, peering, NSGs, a Standard load balancer over two web servers, and a private DNS zone.
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

@allowed(['Standard_B1s', 'Standard_B1ms'])
param vmSize string = 'Standard_B1s'

@description('Also create a small client VM in the second branch, to test reaching the web servers from there.')
param clientVm bool = true

@secure()
@description('VM admin password; labctl generates it. No inbound SSH is opened: use Run Command in the portal.')
param adminPassword string

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: {
    labName: labName
    location: location
    tags: tags
    vmSize: vmSize
    clientVm: clientVm
    adminPassword: adminPassword
  }
}

output url string = lab.outputs.url
output loadBalancerIp string = lab.outputs.loadBalancerIp
output dnsZone string = lab.outputs.dnsZone
output webServers string = lab.outputs.webServers
output clientVm string = lab.outputs.clientVm
