// Ferretería El Tornillo: monitoring. A web shop that logs to Log Analytics and Application Insights, with metric,
// log, activity-log and service-health alerts, an action group and an alert processing rule.
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

@description('Where the alerts are sent.')
param contactEmail string

@minValue(1)
@maxValue(20)
@description('Server errors (HTTP 5xx) in five minutes that fire the metric alert.')
param errorThreshold int = 3

@description('Mute notifications every Sunday 02:00 to 04:00 with an alert processing rule.')
param maintenanceRule bool = true

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: {
    labName: labName
    location: location
    tags: tags
    contactEmail: contactEmail
    errorThreshold: errorThreshold
    maintenanceRule: maintenanceRule
  }
}

output url string = lab.outputs.url
output siteName string = lab.outputs.siteName
output workspaceName string = lab.outputs.workspaceName
output insightsName string = lab.outputs.insightsName
