// Clínica Dental Sonrisa: backup and recovery. A small server with a data folder, protected by a Recovery Services
// vault and a daily policy, plus a Backup vault for comparison.
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

@allowed(['LocallyRedundant', 'GeoRedundant'])
@description('Where the vault keeps backup copies. Set before the first item is protected, and cannot change afterwards.')
param vaultRedundancy string = 'LocallyRedundant'

@description('Protect the server with the daily policy at deployment time (otherwise the class does it).')
param protectVm bool = true

@minValue(1)
@maxValue(30)
@description('Days the daily policy keeps a restore point.')
param retentionDays int = 7

@secure()
@description('VM admin password; labctl generates it. No inbound traffic is opened, so nobody needs it.')
param adminPassword string

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: {
    labName: labName
    location: location
    tags: tags
    vaultRedundancy: vaultRedundancy
    protectVm: protectVm
    retentionDays: retentionDays
    adminPassword: adminPassword
  }
}

// Opens the Recovery Services vault in the portal (backup items, policies, jobs and reports are all there).
output url string = 'https://portal.azure.com/#@/resource${lab.outputs.vaultId}/overview'
output vaultName string = lab.outputs.vaultName
output backupVaultName string = lab.outputs.backupVaultName
output vmName string = lab.outputs.vmName
