// Cooperativa cafetalera: expedientes. Azure Content Understanding in Foundry: the models its analyzers use,
// and synthetic documents and photos to analyze. The class brings its own short audio and video clips.
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

@description('Model deployments (name, model, version, capacity in thousands of tokens per minute), built by labctl.')
param deployments array

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: {
    labName: labName
    location: location
    tags: tags
    deployments: deployments
  }
}

// Opens Content Understanding Studio, where the class connects the resource and runs the analyzers.
output url string = 'https://contentunderstanding.ai.azure.com/'
output aiAccount string = lab.outputs.aiAccount
output storageAccount string = lab.outputs.storageAccount
output container string = 'expedientes'
