// Tour operator: scale and uptime. App Service with autoscale, a staging slot and a health check.
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

@minValue(2)
@maxValue(3)
@description('Most instances autoscale may add.')
param maxInstances int = 3

@description('Probe /health and take an unhealthy instance out of rotation.')
param healthCheck bool = true

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: {
    labName: labName
    location: location
    tags: tags
    maxInstances: maxInstances
    healthCheck: healthCheck
  }
}

output url string = lab.outputs.url
output stagingUrl string = lab.outputs.stagingUrl
output siteName string = lab.outputs.siteName
output planName string = lab.outputs.planName
