// Cooperativa: governance. Policies, a delete lock, a budget and tagged resources in one resource group.
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

@allowed(['one', 'us'])
@description('one = only the lab region; us = the five main US regions.')
param allowedRegions string = 'us'

@description('Deny resources that have no centroCosto tag.')
param requireTag bool = true

@description('Deny storage accounts that are not Standard_LRS.')
param restrictStorage bool = true

@description('Enforce the policies (deny). Off = report only, so students see compliance without blocks.')
param enforce bool = true

@minValue(5)
@maxValue(500)
param budgetUsd int = 20

@description('Receives the budget alerts.')
param contactEmail string

@description('First day of the current month; the budget starts there.')
param budgetStart string = utcNow('yyyy-MM-01T00:00:00Z')

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: {
    labName: labName
    location: location
    tags: tags
    allowedRegions: allowedRegions
    requireTag: requireTag
    restrictStorage: restrictStorage
    enforce: enforce
    budgetUsd: budgetUsd
    contactEmail: contactEmail
    budgetStart: budgetStart
  }
}

// Opens the resource group in the portal, where the policy, lock and budget blades live.
output url string = 'https://portal.azure.com/#@/resource${rg.id}/overview'
output lockedAccount string = lab.outputs.lockedAccount
output policyCount int = lab.outputs.policyCount
