// Invoice scanner — Azure AI Document Intelligence on synthetic invoices and receipts.
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: { labName: labName, location: location, tags: tags }
}

// Opens the Document Intelligence Studio, where students analyze the documents.
output url string = 'https://documentintelligence.ai.azure.com/studio'
output aiAccount string = lab.outputs.aiAccount
output endpoint string = lab.outputs.endpoint
output storageAccount string = lab.outputs.storageAccount
output container string = lab.outputs.container
