// Tourist guide chat: a chat model plus a search index over the tourism office's brochures, in Azure AI Foundry.
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

@allowed(['gpt-5-mini', 'gpt-5-nano', 'gpt-5.4-nano'])
@description('Chat model. Availability changes over time and by region: verify it before class.')
param model string = 'gpt-5-mini'

@minValue(1)
@maxValue(50)
@description('Tokens per minute the deployment may use, in thousands. Keep it low: it is the cost cap.')
param capacityK int = 10

@allowed(['free', 'basic'])
@description('free = one per subscription, small limits; basic = billed by the hour.')
param searchTier string = 'free'

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: {
    labName: labName
    location: location
    tags: tags
    model: model
    capacityK: capacityK
    searchTier: searchTier
  }
}

// Opens Azure AI Foundry, where students chat with the model and attach the brochures.
output url string = 'https://ai.azure.com/'
output aiAccount string = lab.outputs.aiAccount
output deployment string = lab.outputs.deployment
output searchService string = lab.outputs.searchService
output storageAccount string = lab.outputs.storageAccount
