// APIM v2 quick start — public gateway with a sample API. Deploys in minutes.
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

@allowed(['BasicV2', 'StandardV2'])
param sku string = 'BasicV2'

param publisherEmail string
param publisherName string = 'labctl'

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: {
    labName: labName
    location: location
    tags: tags
    sku: sku
    publisherEmail: publisherEmail
    publisherName: publisherName
  }
}

output gatewayUrl string = lab.outputs.gatewayUrl
output sampleRequest string = lab.outputs.sampleRequest
output apimName string = lab.outputs.apimName
