// Pulpería Don Beto — a corner store's inventory in Azure SQL Database (relational data).
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

@allowed(['basic', 'serverless', 'free'])
@description('basic = fixed small price; serverless = pays per second while in use and pauses; free = the Azure SQL free offer (one per subscription).')
param tier string = 'basic'

@secure()
@description('SQL admin password; labctl generates it. Reset it on the server in the portal to sign in by hand.')
param adminPassword string

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: {
    labName: labName
    location: location
    tags: tags
    tier: tier
    adminPassword: adminPassword
  }
}

// The url output opens the database in the portal, where the Query editor lives.
output url string = 'https://portal.azure.com/#@/resource${lab.outputs.databaseId}/overview'
output serverName string = lab.outputs.serverName
output serverFqdn string = lab.outputs.serverFqdn
output adminLogin string = lab.outputs.adminLogin
output database string = lab.outputs.database
