// Repartos Rapidito: containers. A container registry, a container group on Azure Container Instances and a
// container app on Azure Container Apps that scales on HTTP traffic.
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

@allowed(['Basic', 'Standard'])
param registrySku string = 'Basic'

@allowed([0, 1])
@description('Replicas kept running when nobody is calling the app (0 = scale to zero).')
param minReplicas int = 0

@minValue(1)
@maxValue(5)
param maxReplicas int = 3

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: {
    labName: labName
    location: location
    tags: tags
    registrySku: registrySku
    minReplicas: minReplicas
    maxReplicas: maxReplicas
  }
}

output url string = lab.outputs.appUrl
output instanceUrl string = lab.outputs.instanceUrl
output registryName string = lab.outputs.registryName
output registryServer string = lab.outputs.registryServer
output appName string = lab.outputs.appName
