// Clínica: protecting data. Key Vault with RBAC and audit logs, a network security group, locked-down storage and an app identity.
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

@description('Deny public network access to the patient-records storage (students add their own IP to read it).')
param networkLockdown bool = true

@description('Send Key Vault audit events to Log Analytics.')
param auditLogs bool = true

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: {
    labName: labName
    location: location
    tags: tags
    networkLockdown: networkLockdown
    auditLogs: auditLogs
  }
}

// Opens the resource group in the portal: Key Vault, the NSG, Log Analytics and Defender for Cloud are all reachable from there.
output url string = 'https://portal.azure.com/#@/resource${rg.id}/overview'
output vaultName string = lab.outputs.vaultName
output vaultUri string = lab.outputs.vaultUri
output appIdentity string = lab.outputs.appIdentity
output storageAccount string = lab.outputs.storageAccount
