// Feria del Agricultor de Zarcero: voice, vision and image generation in Microsoft Foundry. A project with a
// multimodal chat model, an optional audio model and an optional image-generation model. Azure Speech is part of the resource.
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

@description('Model deployments (name, model, version, capacity in thousands of tokens per minute), built by labctl.')
param deployments array

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: {
    labName: labName
    location: location
    tags: tags
    deployments: deployments
  }
}

// Opens Microsoft Foundry, where the class uses the chat, audio, image and speech playgrounds.
output url string = 'https://ai.azure.com/'
output aiAccount string = lab.outputs.aiAccount
output projectEndpoint string = lab.outputs.projectEndpoint
