// Coffee: seasonal demand. An Azure Machine Learning workspace, a compute cluster that scales to zero, and a sales dataset.
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

@allowed(['Standard_DS2_v2', 'Standard_DS3_v2'])
@description('CPU size of the training cluster (scales to zero when idle).')
param computeSize string = 'Standard_DS2_v2'

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: {
    labName: labName
    location: location
    tags: tags
    computeSize: computeSize
  }
}

// Opens Azure Machine Learning studio on this workspace.
output url string = lab.outputs.studioUrl
output workspace string = lab.outputs.workspace
output compute string = lab.outputs.compute
output storageAccount string = lab.outputs.storageAccount
