#cloud-config
package_update: true
packages:
  - nginx
runcmd:
  - [sh, -c, "echo __PAGE__ | base64 -d > /var/www/html/index.nginx-debian.html"]
  - systemctl enable nginx
  - systemctl restart nginx
