// Taller Los Ángeles — the same appointment page on a virtual machine (IaaS) and on App Service (PaaS).
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

@allowed(['Standard_B1s', 'Standard_B1ms', 'Standard_B2s'])
param vmSize string = 'Standard_B1s'

@description('Free (F1) or Basic (B1) App Service plan.')
@allowed(['F1', 'B1'])
param paasTier string = 'F1'

@description('Shut the VM down every day (teaches that a stopped VM still costs for its disk and IP).')
param autoShutdown bool = true

@description('Daily shutdown time, HHmm in Costa Rica time.')
param shutdownTime string = '2000'

@secure()
@description('VM admin password; labctl generates it. No inbound SSH is opened, so nobody needs it.')
param adminPassword string

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: {
    labName: labName
    location: location
    tags: tags
    vmSize: vmSize
    paasTier: paasTier
    autoShutdown: autoShutdown
    shutdownTime: shutdownTime
    adminPassword: adminPassword
  }
}

output url string = lab.outputs.vmUrl
output vmUrl string = lab.outputs.vmUrl
output paasUrl string = lab.outputs.paasUrl
output vmName string = lab.outputs.vmName
output siteName string = lab.outputs.siteName
