// Soda Doña Rosa — a menu website on Storage static hosting, with a DNS zone for its (example) domain.
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

@allowed(['LRS', 'GRS', 'ZRS'])
@description('Storage redundancy: copies in one datacenter, a paired region, or across zones.')
param redundancy string = 'LRS'

@allowed(['Hot', 'Cool'])
@description('Default access tier: Hot costs more to store and less to read.')
param accessTier string = 'Hot'

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: {
    labName: labName
    location: location
    tags: tags
    redundancy: redundancy
    accessTier: accessTier
  }
}

output url string = lab.outputs.url
output accountName string = lab.outputs.accountName
output dnsZone string = lab.outputs.dnsZone
