// Monthly sales report: a data lake with a year of sales files and a Synapse workspace to query them in place.
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

@description('Open the workspace firewall to every address so Synapse Studio works from the classroom. The data is synthetic; turn it off for anything real.')
param openFirewall bool = true

@secure()
@description('SQL admin password for the workspace; labctl generates it.')
param adminPassword string

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: {
    labName: labName
    location: location
    tags: tags
    openFirewall: openFirewall
    adminPassword: adminPassword
  }
}

// Opens Synapse Studio for the workspace.
output url string = lab.outputs.studioUrl
output dataLake string = lab.outputs.dataLake
output workspace string = lab.outputs.workspace
output sqlEndpoint string = lab.outputs.sqlEndpoint
