// Cooperativa lechera: storage administration. An account with a firewall-ready network, soft delete, versioning,
// a file share and a lifecycle rule, plus a second account ready to receive object replication.
targetScope = 'subscription'

@description('Lab (resource group) name, generated by labctl.')
param labName string

param location string

@description('Tags applied to the resource group and every resource (managedBy, expiresOn, owner, blueprint…).')
param tags object

@allowed(['LRS', 'ZRS', 'GRS'])
param redundancy string = 'LRS'

@description('Create the second account that receives object replication (the class sets up the policy).')
param includeReplica bool = true

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: labName
  location: location
  tags: tags
}

module lab 'lab.bicep' = {
  scope: rg
  name: 'lab'
  params: {
    labName: labName
    location: location
    tags: tags
    redundancy: redundancy
    includeReplica: includeReplica
  }
}

// Opens the main storage account in the portal (networking, SAS, access keys, data protection and file shares are all there).
output url string = 'https://portal.azure.com/#@/resource${lab.outputs.accountId}/overview'
output storageAccount string = lab.outputs.name
output replicaAccount string = lab.outputs.replicaName
output container string = 'documentos'
